#include "CvEngineEnums.h"
#include "PythonAPI/CvPythonExtensions.h"

#include <FInputDevice.h>

#include <pybind11/operators.h>

template<class T>
static auto cyenum(const pybind11::module& m, const char* name)
{
	pybind11::enum_<T> e(m, name, pybind11::arithmetic()); // arithmetic is important! It affects attitude compare in trade diplo.
	e.def(pybind11::self + int());
	e.def(int() + pybind11::self);
	pybind11::implicitly_convertible<int, T>();
	return e;
}

void cvengine::registerEnumsWithPython(pybind11::module& m)
{
#define R(x) value(#x, x)

	using enum FInputDevice::InputType;

	cyenum<FInputDevice::InputType>(m, "InputTypes")
		.R(KB_ESCAPE)
		.R(KB_0)
		.R(KB_1)
		.R(KB_2)
		.R(KB_3)
		.R(KB_4)
		.R(KB_5)
		.R(KB_6)
		.R(KB_7)
		.R(KB_8)
		.R(KB_9)
		.R(KB_MINUS)
		.R(KB_A)
		.R(KB_B)
		.R(KB_C)
		.R(KB_D)
		.R(KB_E)
		.R(KB_F)
		.R(KB_G)
		.R(KB_H)
		.R(KB_I)
		.R(KB_J)
		.R(KB_K)
		.R(KB_L)
		.R(KB_M)
		.R(KB_N)
		.R(KB_O)
		.R(KB_P)
		.R(KB_Q)
		.R(KB_R)
		.R(KB_S)
		.R(KB_T)
		.R(KB_U)
		.R(KB_V)
		.R(KB_W)
		.R(KB_X)
		.R(KB_Y)
		.R(KB_Z)
		.R(KB_EQUALS)
		.R(KB_BACKSPACE)
		.R(KB_TAB)
		.R(KB_LBRACKET)
		.R(KB_RBRACKET)
		.R(KB_RETURN)
		.R(KB_LCONTROL)
		.R(KB_SEMICOLON)
		.R(KB_APOSTROPHE)
		.R(KB_GRAVE)
		.R(KB_LSHIFT)
		.R(KB_BACKSLASH)
		.R(KB_COMMA)
		.R(KB_PERIOD)
		.R(KB_SLASH)
		.R(KB_RSHIFT)
		.R(KB_NUMPADSTAR)
		.R(KB_LALT)
		.R(KB_SPACE)
		.R(KB_CAPSLOCK)
		.R(KB_F1)
		.R(KB_F2)
		.R(KB_F3)
		.R(KB_F4)
		.R(KB_F5)
		.R(KB_F6)
		.R(KB_F7)
		.R(KB_F8)
		.R(KB_F9)
		.R(KB_F10)
		.R(KB_NUMLOCK)
		.R(KB_SCROLL)
		.R(KB_NUMPAD7)
		.R(KB_NUMPAD8)
		.R(KB_NUMPAD9)
		.R(KB_NUMPADMINUS)
		.R(KB_NUMPAD4)
		.R(KB_NUMPAD5)
		.R(KB_NUMPAD6)
		.R(KB_NUMPADPLUS)
		.R(KB_NUMPAD1)
		.R(KB_NUMPAD2)
		.R(KB_NUMPAD3)
		.R(KB_NUMPAD0)
		.R(KB_NUMPADPERIOD)
		.R(KB_F11)
		.R(KB_F12)
		.R(KB_NUMPADEQUALS)
		.R(KB_AT)
		.R(KB_UNDERLINE)
		.R(KB_COLON)
		.R(KB_NUMPADENTER)
		.R(KB_RCONTROL)
		.R(KB_VOLUMEDOWN)
		.R(KB_VOLUMEUP)
		.R(KB_NUMPADCOMMA)
		.R(KB_NUMPADSLASH)
		.R(KB_SYSRQ)
		.R(KB_RALT)
		.R(KB_PAUSE)
		.R(KB_HOME)
		.R(KB_UP)
		.R(KB_PGUP)
		.R(KB_LEFT)
		.R(KB_RIGHT)
		.R(KB_END)
		.R(KB_DOWN)
		.R(KB_PGDN)
		.R(KB_INSERT)
		.R(KB_DELETE)
		.R(NUM_INPUT_TYPE)
		;

	cyenum<NotifyCode>(m, "NotifyCode")
		.R(NOTIFY_CLICKED)
		.R(NOTIFY_DBL_CLICKED)
		.R(NOTIFY_FOCUS)
		.R(NOTIFY_UNFOCUS)
		.R(NOTIFY_CURSOR_MOVE_ON)
		.R(NOTIFY_CURSOR_MOVE_OFF)
		.R(NOTIFY_CHARACTER)
		.R(NOTIFY_SCROLL_UP)
		.R(NOTIFY_SCROLL_DOWN)
		.R(NOTIFY_NEW_HORIZONTAL_STOP)
		.R(NOTIFY_NEW_VERTICAL_STOP)
		.R(NOTIFY_LISTBOX_ITEM_SELECTED)
		.R(NOTIFY_FLYOUT_ITEM_SELECTED)
		.R(NOTIFY_MOUSEMOVE)
		.R(NOTIFY_MOUSEWHEELUP)
		.R(NOTIFY_MOUSEWHEELDOWN)
		.R(NOTIFY_LINKEXECUTE)
		.R(NOTIFY_MOVIE_DONE)
		.R(NOTIFY_SLIDER_NEWSTOP)
		.R(NOTIFY_TABLE_HEADER_SELECTED)
		;

	cyenum<MouseFlags>(m, "MouseFlags")
		.R(MOUSE_STATE)
		.R(MOUSE_LBUTTON)
		.R(MOUSE_RBUTTON)
		.R(MOUSE_SHIFT)
		.R(MOUSE_CONTROL)
		.R(MOUSE_MBUTTON)
		.R(MOUSE_XBUTTON1)
		.R(MOUSE_XBUTTON2)
		.R(MOUSE_EVENT)
		.R(MOUSE_MOUSEMOVE)
		.R(MOUSE_LBUTTONDOWN)
		.R(MOUSE_LBUTTONUP)
		.R(MOUSE_LBUTTONDBLCLK)
		.R(MOUSE_RBUTTONDOWN)
		.R(MOUSE_RBUTTONUP)
		.R(MOUSE_RBUTTONDBLCLK)
		.R(MOUSE_MBUTTONDOWN)
		.R(MOUSE_MBUTTONUP)
		.R(MOUSE_MBUTTONDBLCLK)
		.R(MOUSE_MOUSEWHEELUP)
		.R(MOUSE_MOUSEWHEELDOWN)
		.R(MOUSE_XBUTTONDOWN)
		.R(MOUSE_XBUTTONUP)
		.R(MOUSE_XBUTTONDBLCLK)
		.R(MOUSE_CLICKED)
		.R(MOUSE_DBLCLICKED)
		.R(MOUSE_RELEASED)
		;
}