#include "VersionInfo.h"

#define CV4MINIENGINE_STR(s) #s
#define CV4MINIENGINE_MAKE_VERSIONSTRING(s) L"" CV4MINIENGINE_STR(s)

#ifndef CV4MINIENGINE_VERSION_STRING
#define CV4MINIENGINE_VERSION_STRING dev
#endif

constexpr std::wstring_view cvengine::kEngineVersionString = CV4MINIENGINE_MAKE_VERSIONSTRING(CV4MINIENGINE_VERSION_STRING);