// This file is generated by Cv4MiniEngine/CvGameCoreDLL.

#pragma once

#include <cstdint>

namespace cvbot::enums
{
	namespace Improvement { enum Enum : std::int8_t; }
	namespace Feature { enum Enum : std::int8_t; }
	namespace Terrain { enum Enum : std::int8_t; }
	namespace UnitClass { enum Enum : std::int8_t; }
	namespace UnitType { enum Enum : std::int8_t; }
	namespace Route { enum Enum : std::int8_t; }
	namespace Promotion { enum Enum : std::int8_t; }
	namespace EventTrigger { enum Enum : std::int16_t; }
	namespace Event { enum Enum : std::int16_t; }
	namespace BuildingClass { enum Enum : std::int8_t; }
	namespace BuildingType { enum Enum : std::int16_t; }
	namespace Process { enum Enum : std::int8_t; }
	namespace Bonus { enum Enum : std::int8_t; }
	namespace Specialist { enum Enum : std::int8_t; }
	namespace Build { enum Enum : std::int8_t; }
	namespace Tech { enum Enum : std::int8_t; }
	namespace CivicOptionType { enum Enum : std::int8_t; }
	namespace Civic { enum Enum : std::int8_t; }
	namespace Religion { enum Enum : std::int8_t; }
	namespace GameSpeed { enum Enum : std::int8_t; }
	namespace WorldSize { enum Enum : std::int8_t; }
	namespace Handicap { enum Enum : std::int8_t; }
	namespace CultureLevel { enum Enum : std::int8_t; }
	namespace Victory { enum Enum : std::int8_t; }
	namespace Project { enum Enum : std::int8_t; }
	namespace LeaderTrait { enum Enum : std::int8_t; }
}

namespace cvbot
{
	using EImprovement = enums::Improvement::Enum;
	using EFeature = enums::Feature::Enum;
	using ETerrain = enums::Terrain::Enum;
	using EUnitClass = enums::UnitClass::Enum;
	using EUnitType = enums::UnitType::Enum;
	using ERoute = enums::Route::Enum;
	using EPromotion = enums::Promotion::Enum;
	using EEventTrigger = enums::EventTrigger::Enum;
	using EEvent = enums::Event::Enum;
	using EBuildingClass = enums::BuildingClass::Enum;
	using EBuildingType = enums::BuildingType::Enum;
	using EProcess = enums::Process::Enum;
	using EBonus = enums::Bonus::Enum;
	using ESpecialist = enums::Specialist::Enum;
	using EBuild = enums::Build::Enum;
	using ETech = enums::Tech::Enum;
	using ECivicOptionType = enums::CivicOptionType::Enum;
	using ECivic = enums::Civic::Enum;
	using EReligion = enums::Religion::Enum;
	using EGameSpeed = enums::GameSpeed::Enum;
	using EWorldSize = enums::WorldSize::Enum;
	using EHandicap = enums::Handicap::Enum;
	using ECultureLevel = enums::CultureLevel::Enum;
	using EVictory = enums::Victory::Enum;
	using EProject = enums::Project::Enum;
	using ELeaderTrait = enums::LeaderTrait::Enum;
}
