// This file is generated by Cv4MiniEngine/CvGameCoreDLL.

#pragma once

#include "EnumDefs.h"

#include <array>

namespace cvbot
{
	extern const std::array<const char*, EImprovement::Num> kImprovementNames;
	extern const std::array<const char*, EFeature::Num> kFeatureNames;
	extern const std::array<const char*, ETerrain::Num> kTerrainNames;
	extern const std::array<const char*, EUnitClass::Num> kUnitClassNames;
	extern const std::array<const char*, EUnitType::Num> kUnitTypeNames;
	extern const std::array<const char*, ERoute::Num> kRouteNames;
	extern const std::array<const char*, EPromotion::Num> kPromotionNames;
	extern const std::array<const char*, EEventTrigger::Num> kEventTriggerNames;
	extern const std::array<const char*, EEvent::Num> kEventNames;
	extern const std::array<const char*, EBuildingClass::Num> kBuildingClassNames;
	extern const std::array<const char*, EBuildingType::Num> kBuildingTypeNames;
	extern const std::array<const char*, EProcess::Num> kProcessNames;
	extern const std::array<const char*, EBonus::Num> kBonusNames;
	extern const std::array<const char*, ESpecialist::Num> kSpecialistNames;
	extern const std::array<const char*, EBuild::Num> kBuildNames;
	extern const std::array<const char*, ETech::Num> kTechNames;
	extern const std::array<const char*, ECivicOptionType::Num> kCivicOptionTypeNames;
	extern const std::array<const char*, ECivic::Num> kCivicNames;
	extern const std::array<const char*, EReligion::Num> kReligionNames;
	extern const std::array<const char*, EGameSpeed::Num> kGameSpeedNames;
	extern const std::array<const char*, EWorldSize::Num> kWorldSizeNames;
	extern const std::array<const char*, EHandicap::Num> kHandicapNames;
	extern const std::array<const char*, ECultureLevel::Num> kCultureLevelNames;
	extern const std::array<const char*, EVictory::Num> kVictoryNames;
	extern const std::array<const char*, EProject::Num> kProjectNames;
	extern const std::array<const char*, ELeaderTrait::Num> kLeaderTraitNames;
}
