#pragma once

#include <utility>

namespace cvengine
{
	enum MouseFlags
	{
		MOUSE_STATE = 1,
		MOUSE_LBUTTON = 1,
		MOUSE_RBUTTON = 2,
		MOUSE_SHIFT = 4,
		MOUSE_CONTROL = 8,
		MOUSE_MBUTTON = 0x10,
		MOUSE_XBUTTON1 = 0x20,
		MOUSE_XBUTTON2 = 0x40,
		MOUSE_EVENT = 0x1000,
		MOUSE_MOUSEMOVE = 0x1000,
		MOUSE_LBUTTONDOWN = 0x2000,
		MOUSE_LBUTTONUP = 0x4000,
		MOUSE_LBUTTONDBLCLK = 0x8000,
		MOUSE_RBUTTONDOWN = 0x10000,
		MOUSE_RBUTTONUP = 0x20000,
		MOUSE_RBUTTONDBLCLK = 0x40000,
		MOUSE_MBUTTONDOWN = 0x80000,
		MOUSE_MBUTTONUP = 0x100000,
		MOUSE_MBUTTONDBLCLK = 0x200000,
		MOUSE_MOUSEWHEELUP = 0x4000000,
		MOUSE_MOUSEWHEELDOWN = 0x8000000,
		MOUSE_XBUTTONDOWN = 0x800000,
		MOUSE_XBUTTONUP = 0x1000000,
		MOUSE_XBUTTONDBLCLK = 0x2000000,
		MOUSE_CLICKED = 0x892000,
		MOUSE_DBLCLICKED = 0x2248000,
		MOUSE_RELEASED = 0x1124000,
	};

	constexpr MouseFlags operator|(MouseFlags a, MouseFlags b)
	{
		return MouseFlags(std::to_underlying(a) | std::to_underlying(b));
	}

	enum NotifyCode
	{
		NOTIFY_CLICKED,
		NOTIFY_DBL_CLICKED,
		NOTIFY_FOCUS,
		NOTIFY_UNFOCUS,
		NOTIFY_CURSOR_MOVE_ON,
		NOTIFY_CURSOR_MOVE_OFF,
		NOTIFY_CHARACTER,
		NOTIFY_SCROLL_UP,
		NOTIFY_SCROLL_DOWN,
		NOTIFY_NEW_HORIZONTAL_STOP,
		NOTIFY_NEW_VERTICAL_STOP,
		NOTIFY_LISTBOX_ITEM_SELECTED,
		NOTIFY_FLYOUT_ITEM_SELECTED,
		NOTIFY_MOUSEMOVE = 12,
		NOTIFY_MOUSEWHEELUP = 14,
		NOTIFY_MOUSEWHEELDOWN = 15,
		NOTIFY_LINKEXECUTE = 18,
		NOTIFY_MOVIE_DONE = 0x13,
		NOTIFY_SLIDER_NEWSTOP = 0x14,
		NOTIFY_TABLE_HEADER_SELECTED = 0x15,
	};

	enum class ECvScreen
	{
		NO_SCREEN = -1,

		DOMESTIC_ADVISOR = 0,
		REWARD_SCREEN = 1,
		DAWN_OF_MAN = 2,
		TECH_CHOOSER = 3,
		FOREIGN_ADVISOR = 4,
		FINANCE_ADVISOR = 5,
		WONDER_MOVIE_SCREEN = 6,
		RELIGION_SCREEN = 7,
		INTRO_MOVIE_SCREEN = 8,
		CIVICS_SCREEN = 9,
		DIPLOMACY_SCREEN = 10,
		OPTIONS_SCREEN = 11,
		TECH_SPLASH = 12,
		REPLAY_SCREEN = 13,
		MILITARY_ADVISOR = 14,
		VICTORY_SCREEN = 15,
		TOP_CIVS = 16,
		TUTORIAL_SCREEN = 17,
		INFO_SCREEN = 18,
		ERA_MOVIE_SCREEN = 19,
		ADVISOR_SCREEN = 20,
		HALL_OF_FAME = 21,
		DAN_QUAYLE_SCREEN = 22,
		WORLDBUILDER_SCREEN = 23,
		WORLDBUILDER_DIPLOMACY_SCREEN = 24,
		VICTORY_MOVIE_SCREEN = 25,
		UN_SCREEN = 26,

		SPACE_SHIP_SCREEN = 28,


		CRUSADES_QUEST_SCREEN = 97,

		MAIN_INTERFACE = 99,
		DEBUG_INFO_SCREEN = 100,

		PEDIA_START = 200,
	};
}

