#pragma once

#include <CommonStuff/vec.h>

#include "Core.h"

#include <array>
#include <cstdint>

namespace hecktui
{
	enum class EColour : std::uint8_t
	{
		Black,
		Maroon,
		Green,
		Olive,
		Navy,
		Purple,
		Teal,
		Silver,
		Grey,
		Red,
		Lime,
		Yellow,
		Blue,
		Fuchsia,
		Aqua,
		White,
		// https://vim.fandom.com/wiki/Xterm256_color_names_for_console_Vim
		Grey0,
		NavyBlue,
		DarkBlue,
		Blue3_19,
		Blue3_20,
		Blue1,
		DarkGreen,
		DeepSkyBlue4_23,
		DeepSkyBlue4_24,
		DeepSkyBlue4_25,
		DodgerBlue3,
		DodgerBlue2,
		Green4,
		SpringGreen4,
		Turquoise4,
		DeepSkyBlue3_31,
		DeepSkyBlue3_32,
		DodgerBlue1,
		Green3_34,
		SpringGreen3_35,
		DarkCyan,
		LightSeaGreen,
		DeepSkyBlue2,
		DeepSkyBlue1,
		Green3_40,
		SpringGreen3_41,
		SpringGreen2_42,
		Cyan3,
		DarkTurquoise,
		Turquoise2,
		Green1,
		SpringGreen2_47,
		SpringGreen1,
		MediumSpringGreen,
		Cyan2 = 50,
		Cyan1,
		DarkRed,
		DeepPink4,
		Purple4_54,
		Purple4_55,
		Purple3,
		BlueViolet,
		Orange4,
		Grey37,
		MediumPurple4,
		SlateBlue3_61,
		SlateBlue3_62,
		RoyalBlue1,
		Chartreuse4,
		DarkSeaGreen4_65,
		PaleTurquoise4,
		SteelBlue,
		SteelBlue3,
		CornflowerBlue,
		Chartreuse3_70,
		DarkSeaGreen4_71,
		CadetBlue_72,
		CadetBlue_73,
		SkyBlue3,
		SteelBlue1_75,
		Chartreuse3_76,
		PaleGreen3,
		SeaGreen3,
		Aquamarine3,
		MediumTurquoise,
		SteelBlue1_81,
		Chartreuse2,
		SeaGreen2,
		SeaGreen1_84,
		SeaGreen1_85,
		Aquamarine1,
		DarkSlateGray2,
		DarkRed_88,
		DeepPink4_89,
		DarkMagenta_90,
		DarkMagenta_91,
		DarkViolet,
		Purple_93,
		Orange4_94,
		LightPink4,
		Plum4,
		MediumPurple3_97,
		MediumPurple3_98,
		SlateBlue1,
		Yellow4_100 = 100,
		Wheat4,
		Grey53,
		LightSlateGrey,
		MediumPurple,
		LightSlateBlue,
		Yellow4_106,
		DarkOliveGreen3_107,
		DarkSeaGreen,
		LightSkyBlue3_109,
		LightSkyBlue3_110,
		SkyBlue2,
		Chartreuse2_112,
		DarkOliveGreen3_113,
		PaleGreen3_114,
		DarkSeaGreen3,
		DarkSlateGray3,
		SkyBlue1,
		Chartreuse1,
		LightGreen_119,
		LightGreen_120,
		PaleGreen1_121,
		Aquamarine1_122,
		DarkSlateGray1,
		Red3_124,
		DeepPink4_125,
		MediumVioletRed,
		Magenta3_127,
		DarkViolet_128,
		Purple_129,
		DarkOrange3_130,
		IndianRed_131,
		HotPink3_132,
		MediumOrchid3,
		MediumOrchid,
		MediumPurple2_135,
		DarkGoldenrod,
		LightSalmon3_137,
		RosyBrown,
		Grey63,
		MediumPurple2_140,
		MediumPurple1,
		Gold3_142,
		DarkKhaki,
		NavajoWhite3,
		Grey69,
		LightSteelBlue3,
		LightSteelBlue,
		Yellow3,
		DarkOliveGreen3,
		DarkSeaGreen3_150,
		DarkSeaGreen2_151,
		LightCyan3,
		LightSkyBlue1,
		GreenYellow,
		DarkOliveGreen2,
		PaleGreen1_156,
		DarkSeaGreen2_157,
		DarkSeaGreen1_158,
		PaleTurquoise1,
		Red3_160,
		DeepPink3_161,
		DeepPink3_162,
		Magenta3_163,
		Magenta3_164,
		Magenta2_165,
		DarkOrange3_166,
		IndianRed_167,
		HotPink3_168,
		HotPink2,
		Orchid,
		MediumOrchid1_171,
		Orange3,
		LightSalmon3_173,
		LightPink3,
		Pink3,
		Plum3,
		Violet,
		Gold3_178,
		LightGoldenrod3,
		Tan,
		MistyRose3,
		Thistle3,
		Plum2,
		Yellow3_184,
		Khaki3,
		LightGoldenrod2,
		LightYellow3,
		Grey84,
		LightSteelBlue1,
		Yellow2,
		DarkOliveGreen1_191,
		DarkOliveGreen1_192,
		DarkSeaGreen1_193,
		Honeydew2,
		LightCyan1,
		Red1,
		DeepPink2,
		DeepPink1_198,
		DeepPink1_199,
		Magenta2_200,
		Magenta1,
		OrangeRed1,
		IndianRed1_203,
		IndianRed1_204,
		HotPink_205,
		HotPink_206,
		MediumOrchid1_207,
		DarkOrange,
		Salmon1,
		LightCoral,
		PaleVioletRed1,
		Orchid2,
		Orchid1,
		Orange1,
		SandyBrown,
		LightSalmon1,
		LightPink1,
		Pink1,
		Plum1,
		Gold1,
		LightGoldenrod2_221,
		LightGoldenrod2_222,
		NavajoWhite1,
		MistyRose1,
		Thistle1,
		Yellow1,
		LightGoldenrod1,
		Khaki1,
		Wheat1,
		Cornsilk1,
		Grey100,
		Grey3,
		Grey7,
		Grey11,
		Grey15,
		Grey19,
		Grey23,
		Grey27,
		Grey30,
		Grey35,
		Grey39,
		Grey42,
		Grey46,
		Grey50,
		Grey54,
		Grey58,
		Grey62,
		Grey66,
		Grey70,
		Grey74,
		Grey78,
		Grey82,
		Grey85,
		Grey89,
		Grey93,

		Gray = Grey,
		LightGreen = Lime,
		LightCyan = Aqua,
		Cyan = Teal,
		Brown = Olive,
		LightBlue = Blue,
		LightMagenta = Fuchsia,
		LightRed = Red,
	};

	struct Colour
	{
		EColour code = EColour::Black;
		bool transparent = false;

		constexpr Colour() : transparent(true)
		{
		}

		constexpr Colour(EColour code) : code(code)
		{
		}
	};

	inline constexpr Colour kTransparent{};

	using RGB8 = heck::RGB8;
	using CubeRGB = std::array<int, 3>;
	using RGBF = std::array<float, 3>;

	HECKCONSOLEUI_EXPORT EColour toNonSysColour(EColour);

	HECKCONSOLEUI_EXPORT EColour toColourFromRGB8(RGB8);
	HECKCONSOLEUI_EXPORT RGB8 toRGB8(EColour);

	HECKCONSOLEUI_EXPORT EColour toColourFromRGBF(RGBF);
	HECKCONSOLEUI_EXPORT RGBF toRGBF(EColour);

	HECKCONSOLEUI_EXPORT RGB8 toRGB8(RGBF);

	HECKCONSOLEUI_EXPORT CubeRGB decodeCubeColour(EColour);
	HECKCONSOLEUI_EXPORT EColour encodeCubeColour(CubeRGB);
}